name: sip_kabell_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.16.9
  http: ^0.13.5
  image_picker: ^1.0.7
  path: ^1.8.3
  flutter_typeahead: ^5.2.0


  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  firebase_auth_web: ^5.7.3
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.2.6

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Utility
  go_router: ^10.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.2.5
  carousel_slider: ^5.1.1
  google_fonts: ^4.0.4
  package_info_plus: ^8.0.0


  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/banner3.png
