// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0WcEmlnRemtI0xz9x0wZ2Lrmkwqzbb48',
    appId: '1:1063987728042:web:60fa30f49aae6745088ad3',
    messagingSenderId: '1063987728042',
    projectId: 'sip-kabel-ec1d8',
    authDomain: 'sip-kabel-ec1d8.firebaseapp.com',
    storageBucket: 'sip-kabel-ec1d8.firebasestorage.app',
    measurementId: 'G-6HSY1QHBHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHuAf2rvo7t_v8SOQp_jhOyLatIDotxIs',
    appId: '1:1063987728042:android:7adc28e4b221b189088ad3',
    messagingSenderId: '1063987728042',
    projectId: 'sip-kabel-ec1d8',
    storageBucket: 'sip-kabel-ec1d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOEB-1T5yyhP090YjJWbNXzNmiDM8bDtw',
    appId: '1:1063987728042:ios:e88dcb3090f614ac088ad3',
    messagingSenderId: '1063987728042',
    projectId: 'sip-kabel-ec1d8',
    storageBucket: 'sip-kabel-ec1d8.firebasestorage.app',
    androidClientId: '1063987728042-9uqk7kf7l5s62a7tp3v8kk83tlm9p9qn.apps.googleusercontent.com',
    iosClientId: '1063987728042-edfnkm53njen41duvhccekv1fsvnmk8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipKabellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOEB-1T5yyhP090YjJWbNXzNmiDM8bDtw',
    appId: '1:1063987728042:ios:e88dcb3090f614ac088ad3',
    messagingSenderId: '1063987728042',
    projectId: 'sip-kabel-ec1d8',
    storageBucket: 'sip-kabel-ec1d8.firebasestorage.app',
    androidClientId: '1063987728042-9uqk7kf7l5s62a7tp3v8kk83tlm9p9qn.apps.googleusercontent.com',
    iosClientId: '1063987728042-edfnkm53njen41duvhccekv1fsvnmk8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipKabellApp',
  );

}